msrv = "1.85"
cognitive-complexity-threshold = 25
excessive-nesting-threshold = 5

warn-on-all-wildcard-imports = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
enum-variant-size-threshold = 200
type-complexity-threshold = 250
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
array-size-threshold = 512000
vec-box-size-threshold = 4096
max-trait-bounds = 3
max-struct-bools = 3
max-fn-params-bools = 3
trivial-copy-size-limit = 8
pass-by-value-size-limit = 256
too-large-for-stack = 200
future-size-threshold = 16384

missing-docs-in-crate-items = true
check-private-items = false
